from typing import Any, Awaitable

def get_caller() -> str | None: ...
def get_caller_shell_path() -> str | None: ...
def get_default_owner() -> str | None: ...
def get_request_id() -> str | None: ...
def get_session_key() -> str | None: ...
def get_terminal_key() -> str | None: ...
def get_user_game_id() -> Any: ...
def get_exec_shell_path() -> str | None: ...

def client_command(command: str, data: Any = ...) -> Awaitable[Any]: ...
def client_data(title: str, data: Any, column_formatter: Any = ...) -> Awaitable[None]: ...
def client_html(html: str) -> Awaitable[None]: ...
def client_log(message: str) -> Awaitable[None]: ...
def client_modal(html: str, title: str = ...) -> Awaitable[Any]: ...
def client_modal_close(modal_id: Any) -> Awaitable[None]: ...
def client_script(script: str) -> Awaitable[None]: ...
def client_terminal_script(script: str) -> Awaitable[None]: ...
def set_background(path: str, vertical_align: str = ...) -> Awaitable[None]: ...
def set_background_video(
    url: str,
    vertical_align: str = ...,
    loop: bool = ...,
    muted: bool = ...,
    autoplay: bool = ...,
    plays_inline: bool = ...,
    remove_on_ended: bool = ...,
    toggle_audio: bool = ...,
) -> Awaitable[None]: ...
def set_background_player(
    url: str,
    vertical_align: str = ...,
    loop: bool = ...,
    muted: bool = ...,
    autoplay: bool = ...,
    plays_inline: bool = ...,
    remove_on_ended: bool = ...,
    controls: bool = ...,
) -> Awaitable[None]: ...
def stream(content: str, stream_id: Any) -> Awaitable[None]: ...
def stream_end(stream_id: Any) -> Awaitable[None]: ...
def stream_start(sid: str, label: str) -> Awaitable[Any]: ...
def tool_result(search_term: str, result: Any) -> Awaitable[None]: ...

class _SessionShared:
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def remove(self, key: str) -> None: ...

session_shared: _SessionShared
