from typing import Any, Callable

def get_context() -> Any | None: ...
def get_caller() -> str | None: ...
def get_caller_shell_path() -> str | None: ...
def get_default_owner() -> str | None: ...
def get_entry_point_name() -> str | None: ...
def get_exec_shell_path() -> str | None: ...
def get_owner_usernames() -> list[str]: ...
def get_request_id() -> str | None: ...
def get_script_folder() -> str | None: ...
def get_script_name() -> str | None: ...
def get_session_key() -> str | None: ...
def get_terminal_key() -> str | None: ...
def get_user_game_id() -> int | None: ...
def is_owner(username: str) -> bool: ...
def reset_context() -> None: ...
def set_context(ctx: Any) -> None: ...
def set_exec_shell_path(path: str | None) -> None: ...

def get_uncalled_dynamic_functions(functions_dir: str | None = ...) -> list[dict[str, Any]]: ...
def image_to_base64(image_path: str) -> str: ...
def video_to_base64(video_path: str) -> str: ...

async def client_command(
    command: str,
    data: Any = ...,
    message_type: str = ...,
    is_private: bool = ...,
) -> Any: ...
async def client_data(
    description: str,
    data: Any,
    column_formatter: dict[Any, Any] | None = ...,
) -> Any: ...
async def client_description(
    message: Any,
    level: str = ...,
    is_private: bool = ...,
    location: str | None = ...,
) -> Any: ...
async def client_html(
    content: str,
    modal: bool = ...,
    title: str | None = ...,
) -> Any: ...
async def client_image(
    image_path: str,
    image_format: str | None = ...,
    content: str | None = ...,
    who: str | None = ...,
    max_width: str | None = ...,
) -> Any: ...
async def client_log(
    message: Any,
    level: str = ...,
    message_type: str = ...,
    is_private: bool = ...,
    location: str | None = ...,
) -> Any: ...
async def client_markdown(content: str) -> Any: ...
async def client_modal(content: str, title: str | None = ...) -> str: ...
async def client_modal_close(modal_id: str) -> Any: ...
async def client_onclick(key: str, callback: Callable[..., Any]) -> Any: ...
async def client_script(content: str, is_private: bool = ...) -> Any: ...
async def client_terminal_script(content: str, is_private: bool = ...) -> Any: ...
async def client_upload(key: str, callback: Callable[..., Any]) -> Any: ...
async def client_video(
    video_path: str,
    video_format: str | None = ...,
    content: str | None = ...,
    who: str | None = ...,
) -> Any: ...
async def client_warning(
    message: Any,
    level: str = ...,
    is_private: bool = ...,
    location: str | None = ...,
) -> Any: ...
async def gather_logs() -> bool: ...
async def owner_log(message: str) -> Any: ...
async def set_background(
    image_path: str,
    image_format: str | None = ...,
    vertical_align: str = ...,
    horizontal_align: str = ...,
    background_repeat: str = ...,
    background_size: str = ...,
) -> Any: ...
async def set_background_player(
    video_source: str,
    video_format: str | None = ...,
    vertical_align: str = ...,
    playback_rate: float | None = ...,
    brightness: float | None = ...,
    loop: bool = ...,
    muted: bool = ...,
    autoplay: bool = ...,
    plays_inline: bool = ...,
    remove_on_ended: bool = ...,
    controls: bool = ...,
    replay: bool = ...,
) -> Any: ...
async def set_background_video(
    video_source: str,
    video_format: str | None = ...,
    vertical_align: str = ...,
    playback_rate: float | None = ...,
    brightness: float | None = ...,
    loop: bool = ...,
    muted: bool = ...,
    autoplay: bool = ...,
    plays_inline: bool = ...,
    remove_on_ended: bool = ...,
    toggle_audio: bool = ...,
    replay: bool = ...,
) -> Any: ...
async def stream(message: str, stream_id_param: str) -> Any: ...
async def stream_end(stream_id_param: str) -> Any: ...
async def stream_start(sid: str, who: str) -> str: ...
async def tool_result(name: str, result: Any) -> Any: ...

class _SessionShared:
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def remove(self, key: str) -> None: ...

session_shared: _SessionShared
